SUPPORTED_BLUR_TRANSFORMS = (
    # "AdvancedBlur",
    "Blur",
    "Defocus",
    "GaussianBlur",
    "GlassBlur",
    "MedianBlur",
    "MotionBlur",
    "ZoomBlur",
)

SUPPORTED_CROP_TRANSFORMS = (
    "BBoxSafeRandomCrop",
    "CenterCrop",
    "Crop",
    "CropAndPad",
    "RandomCrop",
    "RandomCropFromBorders",
    "RandomResizedCrop",
    "RandomSizedBBoxSafeCrop",
    "RandomSizedCrop",
)

SUPPORTED_DROPOUT_TRANSFORMS = (
    "ChannelDropout",
    "CoarseDropout",
    "Cutout",
    # "GridDropout",
    # "MaskDropout",
)


SUPPORTED_FUNCTIONAL_TRANSFORMS = (
    "ChannelShuffle",
    "CLAHE",
    "ColorJitter",
    "Downscale",
    "Emboss",
    "Equalize",
    "FancyPCA",
    "GaussNoise",
    "HueSaturationValue",
    "ImageCompression",
    "InvertImg",
    "ISONoise",
    "JpegCompression",
    "MultiplicativeNoise",
    "Normalize",
    "PixelDropout",
    "Posterize",
    "RandomBrightness",
    "RandomBrightnessContrast",
    "RandomContrast",
    "RandomFog",
    "RandomGamma",
    # "RandomGravel",
    # "RandomGridShuffle",
    "RandomRain",
    # "RandomShadow",
    "RandomSnow",
    # "RandomSunFlare",
    "RandomToneCurve",
    "RGBShift",
    "RingingOvershoot",
    "Sharpen",
    "Solarize",
    "Spatter",
    "Superpixels",
    "ToGray",
    "ToSepia",
    "UnsharpMask",
)

SUPPORTED_GEOMETRIC_TRANSFORMS = (
    "Affine",
    "ElasticTransform",
    "Flip",
    "GridDistortion",
    "HorizontalFlip",
    "LongestMaxSize",
    "OpticalDistortion",
    "PadIfNeeded",
    "Perspective",
    # "PiecewiseAffine",
    "RandomRotate90",
    # "Rotate",
    "RandomScale",
    "Resize",
    "SafeRotate",
    "ShiftScaleRotate",
    "SmallestMaxSize",
    "Transpose",
    "VerticalFlip",
)